{
    'name': 'Hospital Caritas Ukraine',
    'summary': '',
    'author': 'Valerii Ivaniuk',
    'website': 'https://www.vivaniuk.pp.ua/',
    'category': 'Customizations',
    'license': 'LGPL-3',
    'version': '18.0.6.4.1',
    'depends': [
        'base',
    ],
    'external_dependencies': {
        'python': [],
    },
    'data': [
        'security/ir.model.access.csv',
        'data/hr_hospital_disease_data.xml',
        'views/hr_hospital_hospital_views.xml',
        'views/hr_hospital_doctor_views.xml',
        'views/hr_hospital_doctor_speciality_views.xml',
        'views/hr_hospital_patient_views.xml',
        'views/hr_hospital_contact_person_views.xml',
        'views/hr_hospital_disease_views.xml',
        'views/hr_hospital_visit_views.xml',
        'views/hr_hospital_wizard_views.xml',
        'views/hr_hospital_disease_report_wizard_views.xml',
        'wizard/hr_hospital_doctor_report_wizard_views.xml',
        'views/hr_hospital_doctor_schedule_wizard_views.xml',
        'views/hr_hospital_mass_reassign_doctor_wizard_views.xml',
        'views/hr_hospital_patient_card_export_wizard_views.xml',
        'views/hr_hospital_reschedule_visit_wizard_views.xml',
        'reports/hr_hospital_doctor_report.xml',
        'reports/hr_hospital_doctor_report_templates.xml',
        'views/hr_hospital_doctor_print_actions.xml',
        'views/hr_hospital_medical_diagnosis_views.xml',
        'views/hr_hospital_menu.xml',
    ],
    'demo': [
        'demo/hr_hospital_hospital_demo.xml',
        'demo/hr_hospital_doctor_speciality_demo.xml',
        'demo/hr_hospital_doctor_demo.xml',
        'demo/hr_hospital_patient_demo.xml',
        'demo/hr_hospital_contact_person_demo.xml',
        'demo/hr_hospital_visit_demo.xml',
        'demo/hr_hospital_diagnosis_demo.xml',
        'demo/hr_hospital_schedule_demo.xml',
        'demo/hr_hospital_doctor_history_demo.xml',
        'demo/hr_hospital_diagnosis_demo_extra.xml',
    ],
    'installable': True,
    'auto_install': False,
    'images': [
        'static/description/icon.png',
    ],
    'application': False,
}
