{
    'name': 'Partner Email Deduplication',
    'version': '18.0.0.1.0',
    'category': 'Sales/CRM',
    'summary': 'Prevents duplicate emails for partners',
    'author': 'web100ry',
    'website': 'https://github.com/web100ry',
    'depends': ['base'],
    'data': [],
    'assets': {},
    'installable': True,
    'application': False,
    'auto_install': False,
    'license': 'LGPL-3',
}
